name: Pull Request Auto Merge

on:
  pull_request:
    branches:
    - master

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  auto-merge:
    runs-on: ubuntu-24.04
    continue-on-error: true

    steps:
    - name: Checkout
      uses: actions/checkout@v4.2.2
      with:
        fetch-depth: 0

    - name: Check for allowlist for auto merge dependencies
      if: ${{ github.event_name == 'pull_request' }}
      id: validate_auto_merge
      run: |
        function set_enable_auto_merge_and_exit() {
          echo "enable_auto_merge=$ENABLE_AUTO_MERGE" >>"$GITHUB_OUTPUT"
          exit 0
        }

        run_cmd() {
          if [ "$DRY_RUN" == "true" ]; then
            echo "[dry-run] $1"
            eval "$1"
          else
            eval "$1"
          fi
        }

        ENABLE_AUTO_MERGE=false
        if git diff ${{ github.event.pull_request.base.sha }}...${{ github.event.pull_request.head.sha }}  --no-renames --diff-filter=AM --quiet -- ':(exclude).github/workflows' ':(exclude).pre-commit-config.yaml' && { [ ${{ github.actor }} == 'dependabot[bot]' ] || [ ${{ github.actor }} == 'renovate[bot]' ]; }; then
          echo "Changed files are eligible for auto merge"
          ENABLE_AUTO_MERGE=true
          run_cmd "gh pr review $PR_URL --approve"
          run_cmd "gh pr merge --auto --squash --delete-branch $PR_URL"
        else
          echo "Changed files are NOT eligible for auto merge"
          ENABLE_AUTO_MERGE=false
          set_enable_auto_merge_and_exit
        fi

        # # Auto merge is allowed only if the PR has a patch or minor label
        # label=$(gh pr view "$PR_URL" --json labels --jq '.labels[] | select (.name == "patch" or .name == "minor").name')
        # if [ -n "$label" ]; then
        #   echo "Label $label exists in the PR, auto merge is enabled"
        #   ENABLE_AUTO_MERGE=true

        # else
        #   echo "Neither patch nor minor label exists in the PR, auto merge is disabled"
        #   ENABLE_AUTO_MERGE=false
        # fi

        set_enable_auto_merge_and_exit
      env:
        PR_URL: ${{ github.event.pull_request.html_url }}
        GH_TOKEN: ${{ github.token }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
