# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Build Check
concurrency:
  group: Build-Check-${{ github.head_ref }}
  cancel-in-progress: true
on:
  pull_request: null
permissions:
  contents: read
jobs:
  build-check:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4.1.1
      with:
        fetch-depth: 0

    - name: Use Node.js 20
      uses: actions/setup-node@v3
      with:
        node-version: 20
        cache: npm

    - name: Build client
      run: |
        npm install
        npm run build
